name: smalltalkCI Self Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        smalltalk:
          - Squeak64-5.3
          - Squeak64-5.2
          - Squeak64-5.1
          - Squeak64-trunk
          - Pharo64-stable
          - Pharo64-alpha
          - Pharo64-9.0
          - Pharo64-8.0
          - Pharo64-7.0
          - Pharo64-6.1
          - Pharo64-6.0
          - Moose64-8.0
          - Moose64-7.0
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Run smalltalkCI self test
        run: smalltalkci -s ${{ matrix.smalltalk }} --self-test
        shell: bash
        if: contains(matrix.smalltalk, 'trunk') == false && contains(matrix.smalltalk, 'alpha') == false && ((contains(matrix.smalltalk, 'Pharo') || contains(matrix.smalltalk, 'Moose')) && matrix.os == 'windows-latest') == false
        timeout-minutes: 15
      - name: Run smalltalkCI self test and ignore failures
        run: smalltalkci -s ${{ matrix.smalltalk }} --self-test || true
        shell: bash
        if: contains(matrix.smalltalk, 'trunk') || contains(matrix.smalltalk, 'alpha') || ((contains(matrix.smalltalk, 'Pharo') || contains(matrix.smalltalk, 'Moose')) && matrix.os == 'windows-latest')
        timeout-minutes: 15
